import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import Navbar from "@/components/navbar";
import "./globals.css";
import "./fonts.css";

export const metadata: Metadata = {
  title: "YOoson - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-gray-900 dark:bg-black dark:text-gray-100 font-sans antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
