import type { Metadata } from "next";
import { ThemeProviders } from "@/components/ThemeProviders"; // pakai komponen client
import Navbar from "@/components/navbar";
import "./globals.css";
import "./fonts.css";

export const metadata: Metadata = {
  title: "YOoson - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProviders>
      <html lang="en" suppressHydrationWarning>
        <body className="bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 font-sans antialiased transition-colors duration-200">
          <Navbar />
          {children}
        </body>
      </html>
    </ThemeProviders>
  );
}
